othermovies,actor,movies
"{tagline:Everything is connected,title:Cloud Atlas,released:2012.0}","{born:1960.0,name:Hugo Weaving}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"
"{tagline:Freedom! Forever!,title:V for Vendetta,released:2006.0}","{born:1960.0,name:Hugo Weaving}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"
"{tagline:Everything that has a beginning has an end,title:The Matrix Revolutions,released:2003.0}","{born:1960.0,name:Hugo Weaving}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"
"{tagline:Free your mind,title:The Matrix Reloaded,released:2003.0}","{born:1960.0,name:Hugo Weaving}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"
"{tagline:Everything that has a beginning has an end,title:The Matrix Revolutions,released:2003.0}","{born:1961.0,name:Laurence Fishburne}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"
"{tagline:Free your mind,title:The Matrix Reloaded,released:2003.0}","{born:1961.0,name:Laurence Fishburne}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"
"{tagline:Everything that has a beginning has an end,title:The Matrix Revolutions,released:2003.0}","{born:1967.0,name:Carrie-Anne Moss}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"
"{tagline:Free your mind,title:The Matrix Reloaded,released:2003.0}","{born:1967.0,name:Carrie-Anne Moss}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"
"{title:Something's Gotta Give,released:2003.0}","{born:1964.0,name:Keanu Reeves}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"
"{tagline:Pain heals, Chicks dig scars... Glory lasts forever,title:The Replacements,released:2000.0}","{born:1964.0,name:Keanu Reeves}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"
"{tagline:The hottest data on earth. In the coolest head in town,title:Johnny Mnemonic,released:1995.0}","{born:1964.0,name:Keanu Reeves}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"
"{tagline:Evil has its winning ways,title:The Devil's Advocate,released:1997.0}","{born:1964.0,name:Keanu Reeves}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"
"{tagline:Everything that has a beginning has an end,title:The Matrix Revolutions,released:2003.0}","{born:1964.0,name:Keanu Reeves}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"
"{tagline:Free your mind,title:The Matrix Reloaded,released:2003.0}","{born:1964.0,name:Keanu Reeves}","{tagline:Welcome to the Real World,title:The Matrix,released:1999.0}"