n
"{tagline:Steve Rogers, a rejected military soldier transforms into Captain America after taking a dose of a ""Super-Soldier serum"". But being Captain America comes at a price as he attempts to take down a war monger and a terrorist organization. ,title:Captain America: The First Avenger,released:2011.0}"
"{born:1950.0,name:Joe Johnston}"
"{born:1964.0,name:Christopher Markus}"
"{born:1978.0,name:Stephen McFeely}"
"{born:1962.0,name:Chris Evans}"
"{born:1980.0,name:Hayley Atwell}"
"{born:1934.0,name:Sebastian Stan}"
"{born:1976.0,name:Tommy Lee Jones}"
"{born:1969.0,name:Hugo Weaving}"
"{born:1961.0,name:Dominic Cooper}"